# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: APEX, HKUST(GZ) & HKUST
  params:
    description: 
  menu:
    main:
      - name: 关于
        url: "#about"
        weight: 1
      - name: 团队
        url: people
        weight: 30
      - name: 出版物
        url: publication
        weight: 40
